import 'package:dio/dio.dart' as dio; // Add prefix
import 'package:form_app/models/form_data.dart';

class ApiService {
  final dio.Dio _dio = dio.Dio(); // Use prefix
  final String _baseUrl =
      'http://31.220.81.182/api/v1/inspections'; // Your API endpoint

  Future<void> submitFormData(FormData formData) async {
    try {
      final response = await _dio.post(
        _baseUrl,
        data: {
          "vehiclePlateNumber": "B 0 LEH",
          "inspectionDate": "2025-04-05T14:30:00Z",
          "overallRating": "8",
          "identityDetails": {
            "namaInspektor": "Totok",
            "namaCustomer": "Prabowo",
            "cabangInspeksi": "Semarang",
          },
          "vehicleData": {
            "merekKendaraan": "Hyundai",
            "tipeKendaraan": "Ioniq 5",
            "tahun": 2023,
            "transmisi": "Automatic",
            "warnaKendaraan": "Silver",
            "odometer": 15000,
            "kepemilikan": "Tangan Pertama",
            "platNomor": "B 1 JR",
            "pajak1Tahun": "2025-10-15",
            "pajak5Tahun": "2028-10-15",
            "biayaPajak": 3500000,
          },
          "equipmentChecklist": {
            "bukuService": true,
            "kunciSerep": false,
            "bukuManual": true,
            "banSerep": true,
            "bpkb": true,
            "dongkrak": true,
            "toolkit": true,
            "noRangka": true,
            "noMesin": true,
          },
          "inspectionSummary": {
            "interiorScore": 9,
            "interiorNotes": "Bersih terawat",
            "eksteriorScore": 8,
            "eksteriorNotes": "Baret halus pintu kanan",
            "kakiKakiScore": 10,
            "kakiKakiNotes": "Aman",
            "mesinScore": 9,
            "mesinNotes": "Suara halus",
            "penilaianKeseluruhanScore": 9,
            "deskripsiKeseluruhan": ["Kondisi sangat baik", "Ada baret halus"],
            "indikasiTabrakan": false,
            "indikasiBanjir": false,
            "indikasiOdometerReset": false,
            "posisiBan": "Bridgestone",
            "merkban": "Bridgestone",
            "tipeVelg": "Original",
            "ketebalanBan": "80%",
            "estimasiPerbaikan": [
              {"namaPart": "Tie Rod Kanan Kiri", "harga": 700000},
              {"namaPart": "Spooring", "harga": 300000},
            ],
          },
          "detailedAssessment": {
            "testDrive": {
              "bunyiGetaran": 10,
              "performaStir": 9,
              "perpindahanTransmisi": 10,
              "stirBalance": 10,
              "performaSuspensi": 9,
              "performaKopling": 10,
              "rpm": 10,
              "catatan": "OK",
            },
            "banDanKakiKaki": {
              "banDepan": 9,
              "velgDepan": 10,
              "discBrake": 10,
              "masterRem": 10,
              "tieRod": 10,
              "gardan": 10,
              "banBelakang": 9,
              "velgBelakang": 10,
              "brakePad": 9,
              "crossmember": 10,
              "knalpot": 10,
              "balljoint": 10,
              "rocksteer": 10,
              "karetBoot": 10,
              "upperLowerArm": 10,
              "shockBreaker": 9,
              "linkStabilizer": 10,
              "catatan": "OK",
            },
            "hasilInspeksiEksterior": {
              "bumperDepan": 8,
              "kapMesin": 10,
              "lampuUtama": 10,
              "panelAtap": 10,
              "grill": 10,
              "lampuFoglamp": 10,
              "kacaBening": 10,
              "wiperBelakang": 10,
              "bumperBelakang": 9,
              "lampuBelakang": 10,
              "trunklid": 10,
              "kacaDepan": 10,
              "fenderKanan": 10,
              "quarterPanelKanan": 10,
              "pintuBelakangKanan": 10,
              "spionKanan": 10,
              "lisplangKanan": 10,
              "sideSkirtKanan": 10,
              "daunWiper": 10,
              "pintuBelakang": 10,
              "fenderKiri": 10,
              "quarterPanelKiri": 10,
              "pintuDepan": 10,
              "kacaJendelaKanan": 10,
              "pintuBelakangKiri": 10,
              "spionKiri": 10,
              "pintuDepanKiri": 10,
              "kacaJendelaKiri": 10,
              "lisplangKiri": 10,
              "sideSkirtKiri": 10,
              "catatan": "Baret halus pintu kanan",
            },
            "toolsTest": {
              "tebalCatBodyDepan": 8,
              "tebalCatBodyKiri": 8,
              "temperatureAC": 4,
              "tebalCatBodyKanan": 5,
              "tebalCatBodyBelakang": 1,
              "obdScanner": 10,
              "tebalCatBodyAtap": 110,
              "testAccu": 10,
              "catatan": "OK",
            },
            "fitur": {
              "airbag": 10,
              "sistemAudio": 9,
              "powerWindow": 10,
              "sistemAC": 10,
              "interior1": 10,
              "interior2": 10,
              "interior3": 10,
              "catatan": "OK",
            },
            "hasilInspeksiMesin": {
              "getaranMesin": 10,
              "suaraMesin": 10,
              "transmisi": 10,
              "pompaPowerSteering": 10,
              "coverTimingChain": 10,
              "oliPowerSteering": 10,
              "accu": 9,
              "kompressorAC": 10,
              "fan": 10,
              "selang": 10,
              "karterOli": 10,
              "oliRem": 10,
              "kabel": 10,
              "kondensor": 10,
              "radiator": 10,
              "cylinderHead": 10,
              "oliMesin": 9,
              "airRadiator": 10,
              "coverKlep": 10,
              "alternator": 10,
              "waterPump": 10,
              "belt": 9,
              "oliTransmisi": 10,
              "cylinderBlock": 10,
              "bushingBesar": 10,
              "bushingKecil": 10,
              "tutupRadiator": 10,
              "catatan": "OK",
            },
            "hasilInspeksiInterior": {
              "stir": 10,
              "remTangan": 10,
              "pedal": 10,
              "switchWiper": 10,
              "lampuHazard": 10,
              "switchLampu": 10,
              "panelDashboard": 9,
              "pembukaKapMesin": 10,
              "pembukaBagasi": 10,
              "jokDepan": 9,
              "aromaInterior": 10,
              "handlePintu": 10,
              "consoleBox": 10,
              "spionTengah": 10,
              "tuasPersneling": 10,
              "jokBelakang": 9,
              "panelIndikator": 10,
              "switchLampuInterior": 10,
              "karpetDasar": 8,
              "klakson": 10,
              "sunVisor": 10,
              "tuasTangkiBensin": 10,
              "sabukPengaman": 10,
              "trimInterior": 9,
              "plafon": 10,
              "catatan": "OK",
            },
          },
          "bodyPaintThickness": {
            "front": "10",
            "rear": {"trunk": 10, "bumper": 10},
            "right": {
              "frontFender": 10,
              "frontDoor": 10,
              "rearDoor": 10,
              "rearFender": 10,
            },
            "left": {
              "frontFender": 10,
              "frontDoor": 10,
              "rearDoor": 10,
              "rearFender": 10,
            },
          },
        },
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        //print('Form data submitted successfully!');
        // TODO: Handle success (e.g., show a success message)
      } else {
        //print('Failed to submit form data: ${response.statusCode}');
        // TODO: Handle errors (e.g., show an error message)
      }
    } catch (e) {
      //print('Error submitting form data: $e');
      // TODO: Handle network errors or exceptions (e.g., show an error message)
    }
  }
}