import 'package:dio/dio.dart' as dio; // Add prefix
import 'package:form_app/models/form_data.dart';

class ApiService {
  final dio.Dio _dio = dio.Dio(); // Use prefix
  final String _baseUrl =
      'http://31.220.81.182/api/v1/inspections'; // Your API endpoint

  Future<void> submitFormData(FormData formData) async {
    try {
      final response = await _dio.post(
        _baseUrl,
        data: {
          "vehiclePlateNumber": formData.platNomor,
          "inspectionDate": formData.tanggalInspeksi?.toIso8601String(),
          "overallRating": formData.penilaianKeseluruhanSelectedValue,
          "identityDetails": {
            "namaInspektor": formData.namaInspektor,
            "namaCustomer": formData.namaCustomer,
            "cabangInspeksi": formData.cabangInspeksi,
          },
          "vehicleData": {
            "merekKendaraan": formData.merekKendaraan,
            "tipeKendaraan": formData.tipeKendaraan,
            "tahun": formData.tahun,
            "transmisi": formData.transmisi,
            "warnaKendaraan": formData.warnaKendaraan,
            "odometer": formData.odometer,
            "kepemilikan": formData.kepemilikan,
            "platNomor": formData.platNomor,
            "pajak1Tahun": formData.pajak1TahunDate?.toIso8601String(),
            "pajak5Tahun": formData.pajak5TahunDate?.toIso8601String(),
            "biayaPajak": formData.biayaPajak,
          },
          "equipmentChecklist": {
            "bukuService": formData.bukuService,
            "kunciSerep": formData.kunciSerep,
            "bukuManual": formData.bukuManual,
            "banSerep": formData.banSerep,
            "bpkb": formData.bpkb,
            "dongkrak": formData.dongkrak,
            "toolkit": formData.toolkit,
            "noRangka":  formData.noRangka,
            "noMesin": formData.noMesin,
          },
          "inspectionSummary": {
            "interiorScore": formData.interiorSelectedValue,
            "interiorNotes": formData.keteranganInterior,
            "eksteriorScore": formData.eksteriorSelectedValue,
            "eksteriorNotes": formData.keteranganEksterior,
            "kakiKakiScore": formData.kakiKakiSelectedValue,
            "kakiKakiNotes": formData.keteranganKakiKaki,
            "mesinScore": formData.mesinSelectedValue,
            "mesinNotes": formData.keteranganMesin,
            "penilaianKeseluruhanScore": formData.penilaianKeseluruhanSelectedValue,
            "deskripsiKeseluruhan": formData.deskripsiKeseluruhan,
            "indikasiTabrakan": formData.indikasiTabrakan,
            "indikasiBanjir": formData.indikasiBanjir,
            "indikasiOdometerReset": formData.indikasiOdometerReset,
            "posisiBan": formData.posisiBan,
            "merkban": formData.merk,
            "tipeVelg": formData.tipeVelg,
            "ketebalanBan": formData.ketebalan,
            "estimasiPerbaikan": formData.repairEstimations.map((estimation) {
              return {
                "namaPart": estimation['repair'],
                "harga": estimation['price'],
              };
            }).toList(),
          },
          "detailedAssessment": {
            "testDrive": {
              "bunyiGetaran": formData.bunyiGetaranSelectedValue,
              "performaStir": formData.performaStirSelectedValue,
              "perpindahanTransmisi": formData.perpindahanTransmisiSelectedValue,
              "stirBalance": formData.stirBalanceSelectedValue,
              "performaSuspensi": formData.performaSuspensiSelectedValue,
              "performaKopling": formData.performaKoplingSelectedValue,
              "rpm": formData.rpmSelectedValue,
              "catatan": formData.testDriveCatatanList,
            },
            "banDanKakiKaki": {
              "banDepan": formData.banDepanSelectedValue,
              "velgDepan": formData.velgDepanSelectedValue,
              "discBrake": formData.discBrakeSelectedValue,
              "masterRem": formData.masterRemSelectedValue,
              "tieRod": formData.tieRodSelectedValue,
              "gardan": formData.gardanSelectedValue,
              "banBelakang": formData.banBelakangSelectedValue,
              "velgBelakang": formData.velgBelakangSelectedValue,
              "brakePad": formData.brakePadSelectedValue,
              "crossmember": formData.crossmemberSelectedValue,
              "knalpot": formData.knalpotSelectedValue,
              "balljoint": formData.balljointSelectedValue,
              "rocksteer": formData.rocksteerSelectedValue,
              "karetBoot": formData.karetBootSelectedValue,
              "upperLowerArm": formData.upperLowerArmSelectedValue,
              "shockBreaker": formData.shockBreakerSelectedValue,
              "linkStabilizer": formData.linkStabilizerSelectedValue,
              "catatan": formData.banDanKakiKakiCatatanList,
            },
            "hasilInspeksiEksterior": {
              "bumperDepan": formData.bumperDepanSelectedValue,
              "kapMesin": formData.kapMesinSelectedValue,
              "lampuUtama": formData.lampuUtamaSelectedValue,
              "panelAtap": formData.panelAtapSelectedValue,
              "grill": formData.grillSelectedValue,
              "lampuFoglamp": formData.lampuFoglampSelectedValue,
              "kacaBening": formData.kacaBeningSelectedValue,
              "wiperBelakang": formData.wiperBelakangSelectedValue,
              "bumperBelakang": formData.bumperBelakangSelectedValue,
              "lampuBelakang": formData.lampuBelakangSelectedValue,
              "trunklid": formData.trunklidSelectedValue,
              "kacaDepan": formData.kacaDepanSelectedValue,
              "fenderKanan": formData.fenderKananSelectedValue,
              "quarterPanelKanan": formData.quarterPanelKananSelectedValue,
              "pintuBelakangKanan": formData.pintuBelakangKananSelectedValue,
              "spionKanan": formData.spionKananSelectedValue,
              "lisplangKanan": formData.lisplangKananSelectedValue,
              "sideSkirtKanan": formData.sideSkirtKananSelectedValue,
              "daunWiper": formData.daunWiperSelectedValue,
              "pintuBelakang": formData.pintuBelakangSelectedValue,
              "fenderKiri": formData.fenderKiriSelectedValue,
              "quarterPanelKiri": formData.quarterPanelKiriSelectedValue,
              "pintuDepan": formData.pintuDepanSelectedValue,
              "kacaJendelaKanan": formData.kacaJendelaKananSelectedValue,
              "pintuBelakangKiri": formData.pintuBelakangKiriSelectedValue,
              "spionKiri": formData.spionKiriSelectedValue,
              "pintuDepanKiri": formData.pintuDepanKiriSelectedValue,
              "kacaJendelaKiri": formData.kacaJendelaKiriSelectedValue,
              "lisplangKiri": formData.lisplangKiriSelectedValue,
              "sideSkirtKiri": formData.sideSkirtKiriSelectedValue,
              "catatan": formData.eksteriorCatatanList,
            },
            "toolsTest": {
              "tebalCatBodyDepan": formData.tebalCatBodyDepanSelectedValue,
              "tebalCatBodyKiri": formData.tebalCatBodyKiriSelectedValue,
              "temperatureAC": formData.temperatureAcMobilSelectedValue,
              "tebalCatBodyKanan": formData.tebalCatBodyKananSelectedValue,
              "tebalCatBodyBelakang": formData.tebalCatBodyBelakangSelectedValue,
              "obdScanner": formData.obdScannerSelectedValue,
              "tebalCatBodyAtap": formData.tebalCatBodyAtapSelectedValue,
              "testAccu": formData.testAccuSelectedValue,
              "catatan": formData.toolsTestCatatanList,
            },
            "fitur": {
              "airbag": formData.airbagSelectedValue,
              "sistemAudio": formData.sistemAudioSelectedValue,
              "powerWindow": formData.powerWindowSelectedValue,
              "sistemAC": formData.sistemAcSelectedValue,
              "interior1": formData.trimInteriorSelectedValue,
              "interior2": formData.aromaInteriorSelectedValue,
              "interior3": 10,
              "catatan": formData.fiturCatatanList,
            },
            "hasilInspeksiMesin": {
              "getaranMesin": formData.getaranMesinSelectedValue,
              "suaraMesin": formData.suaraMesinSelectedValue,
              "transmisi": formData.transmisiSelectedValue,
              "pompaPowerSteering": formData.pompaPowerSteeringSelectedValue,
              "coverTimingChain": formData.coverTimingChainSelectedValue,
              "oliPowerSteering": formData.oliPowerSteeringSelectedValue,
              "accu": formData.accuSelectedValue,
              "kompressorAC": formData.kompressorAcSelectedValue,
              "fan": formData.fanSelectedValue,
              "selang": formData.selangSelectedValue,
              "karterOli": formData.karterOliSelectedValue,
              "oliRem": formData.oilRemSelectedValue,
              "kabel": formData.kabelSelectedValue,
              "kondensor": formData.kondensorSelectedValue,
              "radiator": formData.radiatorSelectedValue,
              "cylinderHead": formData.cylinderHeadSelectedValue,
              "oliMesin": formData.oliMesinSelectedValue,
              "airRadiator": formData.airRadiatorSelectedValue,
              "coverKlep": formData.coverKlepSelectedValue,
              "alternator": formData.alternatorSelectedValue,
              "waterPump": formData.waterPumpSelectedValue,
              "belt": formData.beltSelectedValue,
              "oliTransmisi": formData.oliTransmisiSelectedValue,
              "cylinderBlock": formData.cylinderBlockSelectedValue,
              "bushingBesar": formData.bushingBesarSelectedValue,
              "bushingKecil": formData.bushingKecilSelectedValue,
              "tutupRadiator": formData.tutupRadiatorSelectedValue,
              "catatan": formData.mesinCatatanList,
            },
            "hasilInspeksiInterior": {
              "stir": 10,
              "remTangan": 10,
              "pedal": 10,
              "switchWiper": 10,
              "lampuHazard": 10,
              "switchLampu": 10,
              "panelDashboard": 9,
              "pembukaKapMesin": 10,
              "pembukaBagasi": 10,
              "jokDepan": 9,
              "aromaInterior": 10,
              "handlePintu": 10,
              "consoleBox": 10,
              "spionTengah": 10,
              "tuasPersneling": 10,
              "jokBelakang": 9,
              "panelIndikator": 10,
              "switchLampuInterior": 10,
              "karpetDasar": 8,
              "klakson": 10,
              "sunVisor": 10,
              "tuasTangkiBensin": 10,
              "sabukPengaman": 10,
              "trimInterior": 9,
              "plafon": 10,
              "catatan": "OK",
            },
          },
          "bodyPaintThickness": {
            "front": "10",
            "rear": {"trunk": 10, "bumper": 10},
            "right": {
              "frontFender": 10,
              "frontDoor": 10,
              "rearDoor": 10,
              "rearFender": 10,
            },
            "left": {
              "frontFender": 10,
              "frontDoor": 10,
              "rearDoor": 10,
              "rearFender": 10,
            },
          },
        },
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        print('Form data submitted successfully!');
        // TODO: Handle success (e.g., show a success message)
      } else {
        print('Failed to submit form data: ${response.statusCode}');
        // TODO: Handle errors (e.g., show an error message)
      }
    } catch (e) {
      print('Error submitting form data: $e');
      // TODO: Handle network errors or exceptions (e.g., show an error message)
    }
  }
}
